name: Shomvob CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint and Test All Apps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for accurate versioning

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      # 👉 BACKEND
      - name: Install Backend Deps
        working-directory: ./backend
        run: npm ci

      - name: Lint Backend
        working-directory: ./backend
        run: npm run lint

      - name: Test Backend
        working-directory: ./backend
        run: npm test

      # 👉 FRONTEND
      - name: Install Frontend Deps
        working-directory: ./frontend
        run: npm ci

      - name: Lint Frontend
        working-directory: ./frontend
        run: npm run lint



  deploy-frontend:
    name: Deploy to Vercel
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Vercel Deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT }}
          working-directory: ./frontend
          scope: ${{ secrets.VERCEL_ORG_ID }}        

  deploy-backend:
    name: Deploy to Railway
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy via Railway CLI
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Needed only to install Railway CLI with RubyGems
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Railway Deploy
        run: railway up --service backend --cwd backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
